### PR TITLE
Update `book.py` to conform with PEP 8

### PR DESCRIPTION
**Pull request by xilopaint**

### CODE REVIEW

**Comment by codycodes** [comment]
Thanks for the updates; I really appreciate it 👍 . I didn't get it into the last release as I just saw your PR, but I'm going to test changes now and merge them in :).

**Comment by xilopaint** [comment]
@codycodes hey, you need `icon.png` inside `src` if you symlink this folder to the `workflows` folder otherwise you will run out of icon. You should have in `src` everything is necessary to the workflow's bundle.

**Comment by xilopaint** [comment]
Also, why do you have two instances one instance of `info.plist` in `src` and another one in the root level? You just need it in `src`.

**Comment by codycodes** [comment]
@xilopaint thanks for letting me know! I think I understand what you mean by symlinking now; to clarify though:

A dev can symlink the `./src` folder to a "blank" alfred workflow folder (`.../user.workflow*`) as an easy way to start working on some code? This would make sense to me. I got confused when my icon vanished and I wasn't sure how to set this up. I'll add those changes in; thanks for catching this!

**Pull request merged**
